language: groovy

jdk:
    - oraclejdk7

env:
    - GRAILS_VERSION=2.3.5

before_install:
    - mkdir -p ~/.m2 ~/.grails
    - cd ~/.m2
    - bash -c '{ curl http://files.thehyve.net/caches/grails_${GRAILS_VERSION}_mvncache.tar.gz  | tar xzf -; } || true'
    - cd -

install:
    - cd ~/.grails
    - curl -O http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-${GRAILS_VERSION}.zip
    - unzip -q grails-${GRAILS_VERSION}.zip
    - export GRAILS_HOME=~/.grails/grails-${GRAILS_VERSION}
    - cd -
    - ./install_branch_coreapi

# uncomment the lines if you add test matrix with more than 1 grails version/jdk
script:
#    - ${GRAILS_HOME}/bin/grails clean
#    - ${GRAILS_HOME}/bin/grails upgrade --non-interactive
    - "${GRAILS_HOME}/bin/grails package --non-interactive --stacktrace"
    - cd transmart-core-db-tests
#    - ${GRAILS_HOME}/bin/grails clean
#    - ${GRAILS_HOME}/bin/grails upgrade --non-interactive
    - ${GRAILS_HOME}/bin/grails test-app --non-interactive --stacktrace

notifications:
  hipchat:
    rooms:
      secure: xcYrNzgEMcURuFoD7M2IB4jra+520rt/lDwSbLATSRs/NmyXoJ/cqJH/XcsIcsnF/WfWGQRPDOffMRFMTwurb2FKZC+f25V/Gvcb93tqT2XUx7Z63DJ7dJVgVHgTcs36T/GrNYwytqn01fPZonM8skcWdbJy97K3x3VyjvyCk5A=
    on_success: change
    on_failure: always
